routes/web.php
<?php


use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;




Route::domain('test1')->group(function () {
    Route::get('create_landing/{create_landing}', [LandingController::class, 'show'])->name('test1');
});
Route::domain('test2')->group(function () {
    Route::get('create_landing/{create_landing}', [LandingController::class, 'show'])->name('test2');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->middleware('auth')->group(function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/users', UserController::class);
    Route::resource('/create_landing', LandingController::class)->names('landing');
    Route::get('/test', [TestController::class, 'index']);


});

Auth::routes();

Route::resource('/create-landing', LandingController::class)->names('lending');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'bday',
        'image',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function  role()
    {
        return $this->belongsTo(Role::class);

    }

    public function users()
    {
        return $this->belongsTo(Landing::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Users\CreateRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index',compact('users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $dataToStore = $request->validated();
        $dataToStore["password"] = Hash::make($request->password);
        $user = User::create($dataToStore);
        if ($user) {
            return redirect()->route('users.index')->with('success', 'User created successfully');
        } else {
            return back()->withErrors(['msd' => 'Someting was wrong'])->withInput();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateRequest $request, User $user)
    {
        $user->update($request->validated());
        if ($user) {
            return redirect()->route('users.index')->with('success', 'User created successfully');
        } else {
            return back()->withErrors(['msd' => 'Someting was wrong'])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        if ($user) {
            return redirect()->route('users.index')->with('success', 'User deleted successfully');
        } else {
            return back()->withErrors(['msd' => 'Someting was wrong'])->withInput();
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create users')
@section('content')



    <div class="container mt-5">
        <div class="row pt-5">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h5 class="title">Create users</h5>
                    </div>
                    <div class="card-body">
                        <form action="{{route('users.store')}}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-md-3 px-1">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="text" name="name" class="form-control" placeholder="Username"
                                               value="{{old('name')}}">
                                    </div>
                                    @error('name')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror

                                </div>
                                <div class="col-md-4 pl-1">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email address</label>
                                        <input type="email" name="email" class="form-control" placeholder="Email"
                                               value="{{old('email')}}">
                                    </div>
                                    @error('email')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-4 pl-1">
                                    <div class="form-group">
                                        <label for="exampleInputPassword">Password</label>
                                        <input type="password" name="password" class="form-control"
                                               placeholder="Password" value="{{old('password')}}">
                                    </div>
                                    @error('password')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 pl-1">
                                    <div class="form-group">
                                        <label for="exampleInputText">Role</label>
                                        <input type="role"  name="role" class="form-control" id="exampleInputRole"


                                        </input>

                                    </div>
                                    @error('role_id')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="row">
                                <button type="submit" class="btn mx-auto">SAVE</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>



@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'users')
@section('content')

    <div class="container mt-5">
        <div class="row pt-5">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h5 class="title">Create users</h5>
                    </div>
                    <div class="card-body">
                        <form action="{{route('users.update', $user)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-md-3 px-1">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="text" name="name" class="form-control" placeholder="Username"
                                               value="{{old('name', $user->name)}}">
                                    </div>
                                    @error('name')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror

                                </div>
                                <div class="col-md-4 pl-1">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email address</label>
                                        <input type="email" name="email" class="form-control" placeholder="Email"
                                               value="{{old('email', $user->email)}}">
                                    </div>
                                    @error('email')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-4 pl-1">
                                    <div class="form-group">
                                        <label for="exampleInputPassword">Password</label>
                                        <input type="password" name="password" class="form-control"
                                               placeholder="Password" value="{{old('password', $user->password)}}">
                                    </div>
                                    @error('password')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="row">
                                <button type="submit" class="btn mx-auto">SAVE</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')
@section('title', 'users')
@section('content')


    <div class="container mt-5">
        <div class="row pt-5">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header justify-content-between">
                        <h4 class="card-title float-left"> Simple Table</h4>
                        <a href="{{ route('users.create') }}" class="btn float-right">Create users</a>
                    </div>
                    @if(session('success'))
                        <div class="alert alert-success">{{ session('success') }}</div>
                    @endif
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>Name</th>
                                <th>Email</th>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                <tr onclick="location.href='{{ route('users.show',$user) }}'" style="cursor: pointer;">
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>






@endsection

resources/views/admin/users/show.blade.php
@extends('admin.layouts.app')
@section('title')
    {{ $user->name }}
@section('content')

    <div class="container mt-5">
        <div class="row pt-5">
            <div class="col-md-4">
                <div class="card card-user">
                    <div class="image">
                        <img src="{{ asset('/assets/img/bg5.jpg') }}" alt="...">
                    </div>
                    <div class="card-body">
                        <div class="author">
                            <a href="#">
                                <img class="avatar border-gray" src="{{ asset('/assets/img/mike.jpg') }}" alt="...">
                                <h5 class="title">{{ $user->name }}</h5>
                            </a>
                            <p class="description">
                                {{ $user->email }}
                            </p>
                        </div>

                    </div>
                    <hr>
                    <div class="card-footer">
                    <div class="row text-center">
                        <a href="{{ route('users.edit', $user) }}" class="btn mx-auto">Edit</a>
                        <form action="{{ route('users.destroy', $user) }}" method="POST"
                              id="deleteForm-{{ $user->id }}" style="display: none">
                            @csrf
                            @method('DELETE')
                        </form>
                        <button class="btn btn-danger" onclick="
                            if(confirm('Do you want to delete this user?')){
                            event.preventDefault();
                            document.getElementById('deleteForm-{{ $user->id }}').submit();
                            }else{
                            event.preventDefault();
                            }">Delete user
                        </button>
                    </div>
                </div>
            </div>
        </div>
@endsection