routes/web.php
<?php


use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;




Route::domain('test1')->group(function () {
    Route::get('create_landing/{create_landing}', [LandingController::class, 'show'])->name('test1');
});
Route::domain('test2')->group(function () {
    Route::get('create_landing/{create_landing}', [LandingController::class, 'show'])->name('test2');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->middleware('auth')->group(function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/users', UserController::class);
    Route::resource('/create_landing', LandingController::class)->names('landing');
    Route::get('/test', [TestController::class, 'index']);


});

Auth::routes();

Route::resource('/create-landing', LandingController::class)->names('lending');

app/Models/Landing.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Landing extends Model
{
    use HasFactory;
    protected $fillable = [
        'user_id',
        'shablon_id',
        'title',
        'title_2',
        'image',
        'content',
        'domain',
    ];

    public function users()
    {
        return $this->hasOne(User::class);
    }
    public function shablon()
    {
        return $this->belongsTo(Shablon::class,'shablon_id','id');
    }
}

app/Http/Controllers/LandingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LandingRequest;
use App\Models\Article;
use App\Models\Landing;
use App\Models\Shablon;
use Faker\Provider\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LandingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $landings = Landing::all();
        return view('admin.landing.index', compact('landings'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $shablones = Shablon::all();
        return view('admin.landing.create', compact('shablones'));



    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(LandingRequest $request)
    {


        $params = $request->all();

        unset($params['image']);
        if ($request->has('image')) {
            $params['image'] = $request->file('image')->store('products');
        }

       Landing::create($params);

        if ($params) {
            return redirect()->route('landing.index')->with('success', 'Landing created successfully');
        } else {
            return back()->withErrors(['msd' => 'Someting was wrong'])->withInput();
        }


    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Landing $lending
     * @return \Illuminate\Http\Response
     */
    public function show(Landing $create_landing)
    {

        return view('admin.landing.show', compact('create_landing'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Landing $landing
     * @return \Illuminate\Http\Response
     */
    public function edit(Landing $landing)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Landing $lending
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Landing $landing)
    {
        $path =  public_path().'\images\\';
        $file = $request->file('file');
        $filename = str_random(20) .'.' . $file->getClientOriginalExtension() ?: 'png';
        $img = Image::make($file);
        $img->save($path . $filename);
        echo '/images/'.$filename;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Landing $lending
     * @return \Illuminate\Http\Response
     */
    public function destroy(Landing $lending)
    {

    }
}

resources/views/admin/landing/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create users')
@section('content')



    <div class="container">
        <div class="row pt-5">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h5 class="title">Create Lending</h5>
                    </div>

                    <div class="card-body">
                        <form action="{{route('landing.store')}}" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            @csrf
                            <div class="row">
                                <div class="col-md-3 px-1">
                                    <div class="form-group">
                                        <label>Title</label>
                                        <input type="text" name="title" class="form-control" placeholder="title"
                                               value="{{old('name')}}">
                                    </div>
                                    @error('title')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror

                                </div>
                                <div class="col-md-4 pl-1">
                                    <div class="form-group">
                                        <label>Title_2</label>
                                        <input type="text" name="title_2" class="form-control" placeholder="title_2"
                                               value="{{old('title_2')}}">
                                    </div>
                                    @error('title_2')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-3 px-1">
                                    <div class="form-group">
                                        <label for="shablon_id">Shablon</label>

                                        <select name="shablon_id" id="shablon_id" class="form-control text-danger"
                                                style="height: 37px">
                                            @foreach($shablones as $shablone)

                                                <option value="{{$shablone->id}}">
                                                    {{$shablone->name}}
                                                </option>
                                            @endforeach

                                        </select>

                                    </div>
                                    @error('shablon')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror

                                </div>

                                <div class="input-group row">
                                    <label for="image" class="col-sm-2 col-form-label">Картинка: </label>
                                    <div class="col-sm-10">
                                        <label class="btn btn-default btn-file">
                                            Загрузить <input type="file" style="display: none;" name="image" id="image">
                                        </label>
                                    </div>
                                </div>
                                <br>
                                @error('image')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-3 px-1">
                                <div class="form-group">
                                    <label for="text">Content</label><br/>
                                    <textarea name="content" id="content"></textarea><br/>
                                </div>
                                @error('content')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-3 px-1">
                                <div class="form-group">
                                    <label>Domain</label>
                                    <select name="domain" id="domain" class="form-control" style="height: 37px">
                                        <option>
                                            test1
                                        </option>
                                        <option>
                                            test2
                                        </option>
                                    </select>
                                </div>
                                @error('domain')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="row">
                                <button type="submit" class="btn mx-auto">SAVE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/landing/index.blade.php
@extends('admin.layouts.app')
@section('title', 'lending')
@section('content')


    <div class="container mt-5">
        <div class="row pt-5">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header justify-content-between">
                        <h4 class="card-title float-left"> Simple Table</h4>
                        <a href="{{ route('landing.create') }}" class="btn float-right">Create landing</a>
                    </div>
                    @if(session('success'))
                        <div class="alert alert-success">{{ session('success') }}</div>
                    @endif
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>Id</th>
                                <th>Title</th>
                                <th>Domain</th>
                                </thead>
                                <tbody>
                                @foreach($landings as $landing)
                                    <tr onclick="location.href='{{ route($landing->domain,$landing) }}'"
                                        style="cursor: pointer;">
                                        <td>{{$landing->id}}</td>
                                        <td>{{$landing->title}}</td>
                                        <td>{{$landing->domain}}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>






@endsection

resources/views/admin/landing/show.blade.php
@extends('admin.layouts.'.$create_landing->shablon->name)